name:                constraint-reader
version:             0.1.0.0
github:              "githubuser/constraint-reader"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md

default-extensions:
- ConstraintKinds
- DataKinds
- DeriveGeneric
- ConstraintKinds       
- FlexibleContexts      
- FlexibleInstances
- FunctionalDependencies
- KindSignatures        
- LambdaCase
- MonoLocalBinds
- MultiParamTypeClasses
- OverloadedStrings
- RankNTypes            
- UndecidableInstances  
- ScopedTypeVariables   
- TypeOperators

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- constraints
- containers
- lens
- mtl
- redis-io
- servant-server
- string-conv
- tinylog
- transformers
- warp

library:
  source-dirs: src

executables:
  server:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - constraint-reader

tests:
  constraint-reader-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - constraint-reader
    - hspec
