name:                constraint-reader
version:             0.1.0.0
github:              "githubuser/constraint-reader"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/constraint-reader#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- constraints
- containers
- lens
- mtl
- transformers

library:
  source-dirs: src

executables:
  constraint-reader-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - constraint-reader

tests:
  constraint-reader-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - constraint-reader
    - hspec
